### ISSUE TITLE
Studentenportal Compose and Conf for Production

### ISSUE THREAD

**Issue by fabianhauser** [studentenportal/deploy-new#11]
Create Docker Compose files to run the Studentenportal:

- `postgres`
- `studentenportal`

**Comment by mattbaumann** [comment]
The issue suggests that no docker compose file is available. As far as I know, there is already a such file under `roles/studentenportal/templates/production.j2.yaml`. That file needs certainly some adjustments, but for those changes to happen, the issues #6, #21 have to be done first (requirement).
