### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fabianhauser** [studentenportal/deploy-new#16]
- [x] VM-Environment
- [x] Encryption
- [x] Deployments
- [x] Data folders etc.

**Comment by mattbaumann** [comment]
Should the documentation exist in the following places:
* Documentation folder like https://github.com/studentenportal/deploy-new/files/docs
* Repository wiki
* documentation repository

I would suggest to create a docs/ folder and put everything in there. But what's your preference?
