### ISSUE TITLE
Docker Swarm Setup

### ISSUE THREAD

**Issue by fabianhauser** [studentenportal/deploy-new#5]
Run Docker Swarm on Host.

**Comment by mattbaumann** [comment]
You're right it is scalable to multiple machines. Still, it is also usable for a single host machine. It has it's advantages even for a single-host setup: Fail-over support and container auto-restart, resource usage limits for containers and configuration improvements compared to standard-mode.
Greetings Matt

**Comment by mattbaumann** [comment]
@fabianhauser Is this Issue still open?

**Comment by fabianhauser** [comment]
@mattbaumann  no, I think we can close it 🙂
